language: node_js
sudo: false
node_js:
- 6.0
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: hPMCT0Z87AdPxBWS4xlU6vnGJpv/mzGMBuh/Iyoe2l0CMES6ZKfZMv3TxdKXY10JJXpE9RCtyGzzxLaZNpypQbfG7nUu1JZ5GD8TvfhDMMwCEJswaGPVuEfGqpPF63uKP9KP//Fap6P4ptMjZ884Mvdbi94b4tIOw781AFjbz0p1dOrqXXvOU0b4PcLO7oa07NiURGM4ubywR5dLgUs6vx3ADaRyLdHe3NuiGR2631NWmQgHyLUjS4QRm72MjpScZUQycNwT30sAH7ar62RvslDmSF2sFc/Q98SHZLK3iJvhhE3qupNMdDhl82VluYJal0GYIwkB2TWu3EBUGuAaFYhXxJBBgSXy0KoU5GoMqZ9nKC4c4tbWElO9R0U2x+ASDF/F5i/dJRHkc9xjLjPNGMQ8qXDVkBLbBCcrrOBe0Ee0NSNItAtaMS+4zhNzjm0WV4UcE1s3U7UDQVxEIO+OPCqCpyKBcQ+vblsgLISsNEUaZKXssKXn7P2T0twZIEKrwMhpeO+YwXLLaU5FJDTudbf/HBKLJKYA/+Yfk3qH1FLrG78OOLAsP4DthVsNsLALem38UaRLiwI15K9LEGG4knHiwqaU1US7IX3oFZZBBOeeQ7P2v7OjY/xvIaDDhnBTra2bk7zTUZIn7PUujVGEGfieRzacLPyRq7X68pkB5pA=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - secure: WxZP8MVmrcLZOkkRxxs2CnKXisN4MClwjLfgTheTi5rqROgcpjNO/r/uqopUBIJqDQ5BgBE1Z1Q5I3oX6p1ObXtpJ8DAwIu5tmgJAEPpm7pIY7q93gBBNNCIlUVdNrzvviKSMJMdeXiUSwDTGXCQdXf6sWtt4VkdwzbJ1fF0OvouCWNk8o6kicgUcdGzkRjdC+iUyRKuG+U6UmnwQG4y5jIZTYd1hDYfxaA3jouwoP8hlLtHkOM1j4cB2D3OIikpzXIXs0c86mModAcX43wosvgLEo4KcJX4lH6tGfLBtFmJ6dN1/4VEEBfp1xAeZGlnpfX8C/7CONsHVZ0D+V+jiU7+blS+jiXxjYX/kI/4Sp2BGskxQwqrWqvbJYaxXJ9DeQHwOiiw48OlShqa050utQeF2/btguY7Sgq99e41UdbozLm+rN7L2DMwZHudIag6oPO2p/xTDjulOcQsEySjA5bzcpglVwolsnJ7Y2P3umbzgAIQbjoRDAmyugFp1vsL1ysiVS/sPo8H/Yic5mJYvpMACZE0QVw1ITF1QuffksUN01lX9hKo7D1kclqTi526a2qjIDRRtnnEdUqUR2Li+mBJL5XjaHpN1dhjM9jC33N60mVFIlBFz6PGoi+A6EQiOnH0XnPkpts93qVQtvi2vsVD5oSmQsYIPu2ZmRX7u20=
