language: node_js
sudo: false
node_js:
- 4.2
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: I7MhEd++LqQyxQcivH7thVwazRHmV1By4TzjdKicHHur4qHaQzjiq5a5pM7LtPzrDbgxZapBwA/9okz13iSGeqG+/Nks8Nc2ac1wGOpnewnOSNnCw4e8tJT7Ug88s5cdcIfKeA0GhzUrRie5xEADBk1+9T+UXUujGiUNYcVftmqwV2xEHeE2FqjLGat0OLLx33llpM7ppt3pC00W7dRz/1IEY1Ov/U4lSqEqlppGfbLhi3X7SrgK66eqAiBS21lHUc2EF+/9Z5cebYjVMB6Wlbb6DcbYsm2rUEXiNmKu23P89yOBgLx9VEImDnyfOAfwGXX0H8fHgDXXC0dQboC9pCcBMbe6v4PH9zg0qs2pfUbsBTEX8m376dI1jm8RZhwVAQ0o1wsqLe0d11+p9hEROp0vs4Vgi7Uern7Fzyvpsi/b/ZpxIxbldqbhyb9GVgcrepfBvG3OFCVxNTcjYjyUjn1BATHZA9MdFQgsZTf//AjsbuQp6KGEPzCUTRLlzc5TvJ6LwsPw5Kvbj5hTLUblcgbPNTQH31vcHxkqWaQ8cnwSFinjiKJtdYn5SCHHpMLxdGSg2Pr16mNP+uByf6/A7tpb304TOJGzv3WQdZrwaOTG0KFRIGb4Lurjn+sZXzIsKkboUsJDijdnuxOLCl5a7aPT0JfP+I2IR0GHcAdpG0M=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - secure: WxZP8MVmrcLZOkkRxxs2CnKXisN4MClwjLfgTheTi5rqROgcpjNO/r/uqopUBIJqDQ5BgBE1Z1Q5I3oX6p1ObXtpJ8DAwIu5tmgJAEPpm7pIY7q93gBBNNCIlUVdNrzvviKSMJMdeXiUSwDTGXCQdXf6sWtt4VkdwzbJ1fF0OvouCWNk8o6kicgUcdGzkRjdC+iUyRKuG+U6UmnwQG4y5jIZTYd1hDYfxaA3jouwoP8hlLtHkOM1j4cB2D3OIikpzXIXs0c86mModAcX43wosvgLEo4KcJX4lH6tGfLBtFmJ6dN1/4VEEBfp1xAeZGlnpfX8C/7CONsHVZ0D+V+jiU7+blS+jiXxjYX/kI/4Sp2BGskxQwqrWqvbJYaxXJ9DeQHwOiiw48OlShqa050utQeF2/btguY7Sgq99e41UdbozLm+rN7L2DMwZHudIag6oPO2p/xTDjulOcQsEySjA5bzcpglVwolsnJ7Y2P3umbzgAIQbjoRDAmyugFp1vsL1ysiVS/sPo8H/Yic5mJYvpMACZE0QVw1ITF1QuffksUN01lX9hKo7D1kclqTi526a2qjIDRRtnnEdUqUR2Li+mBJL5XjaHpN1dhjM9jC33N60mVFIlBFz6PGoi+A6EQiOnH0XnPkpts93qVQtvi2vsVD5oSmQsYIPu2ZmRX7u20=
